<?
$aMenuLinks = Array(
	Array(
		"Вакансии", 
		SITE_DIR."/servise/job/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,3,4,6,7,5))" 
	),
	Array(
		"Контакты", 
		SITE_DIR."/servise/contacts/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,3,4,6,7,5))" 
	),
	Array(
		"Новости", 
		SITE_DIR."/servise/news/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,3,4,6,7,5))" 
	),
	Array(
		"Агенты", 
		SITE_DIR."/servise/agents.php", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,3,4,6,7,5))" 
	)
);
?>